-- MySQL Script generated by MySQL Workbench
-- Sat May 12 16:51:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lookify_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lookify_db` ;

-- -----------------------------------------------------
-- Schema lookify_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lookify_db` DEFAULT CHARACTER SET utf8 ;
USE `lookify_db` ;

-- -----------------------------------------------------
-- Table `lookify_db`.`song`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lookify_db`.`song` ;

CREATE TABLE IF NOT EXISTS `lookify_db`.`song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `artist` VARCHAR(45) NOT NULL,
  `rating` DOUBLE NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
